### ISSUE TITLE
Error in ssh 

### ISSUE THREAD

**Issue by felipeoliveiradev** [matzeeable/wp-reactjs-starter#15]
![image](https://user-images.githubusercontent.com/47610299/57643510-44b58d00-7590-11e9-8be7-634ed539b2a9.png)

**Comment by janisii** [comment]
Temporary fix

Edit file /usr/local/lib/node_modules/create-wp-react-app/lib/create.js
Find line starting with repository and change to: 

`repository = 'https://github.com/matzeeable/wp-reactjs-starter.git',`

**Comment by matzeeable** [comment]
Hi @janisii,

Thanks for the report. I have already implemented that fix but I see that I never released the new version on npm, sorry (it was my second npm module so I were not so familar with it). I will release it today...

I close this issue because it is related to https://github.com/matzeeable/create-wp-react-app/issues/4
